language: objective-c
osx_image: xcode7.1
script: xcodebuild -project Marklight.xcodeproj -scheme Marklight -destination 'platform=iOS Simulator,name=iPhone 6' -enableCodeCoverage YES clean build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
